# Generated by Django 3.2 on 2021-05-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210504_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='user',
            new_name='staff',
        ),
    ]
