# Generated by Django 3.2 on 2021-05-06 00:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_department_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='staff',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_head',
            field=models.EmailField(max_length=254),
        ),
    ]
