# Generated by Django 3.2 on 2021-05-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210506_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_head',
            field=models.CharField(choices=[(1, 'admin@aljaybiosciences.com'), (5, 'drei@gmail.com'), (24, 'joke@gmail.com')], max_length=150),
        ),
    ]
