# Generated by Django 3.2 on 2021-05-15 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_department_department_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_head',
            field=models.CharField(choices=[(1, 'admin@aljaybiosciences.com'), (5, 'drei@gmail.com'), (24, 'joke@gmail.com'), (25, 'marie@gmail.com')], max_length=150),
        ),
        migrations.AlterField(
            model_name='department',
            name='staff',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
