# Generated by Django 3.2 on 2021-05-18 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filings', '0035_delete_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(default=0)),
                ('approver', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Approve'), ('3', 'Rejected')], default='1', max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('filing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filings.filing')),
            ],
        ),
    ]
