# Generated by Django 3.2 on 2021-05-21 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0036_remove_filing_status'),
        ('approvals', '0002_alter_approval_filing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='filing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='filings.filing'),
        ),
    ]
