export const USER_FILING_REQUEST = "USER_FILING_REQUEST";
export const USER_FILING_SUCCESS = "USER_FILING_SUCCESS";
export const USER_FILING_FAIL = "USER_FILING_FAIL";

//Get List of Leave Constants
export const USER_FILING_LIST = "USER_FILING_LIST";

//Edit Leave Constants
export const USER_EDIT_FILING_REQUEST = "USER_EDIT_FILING_REQUEST";
export const USER_EDIT_FILING_SUCCESS = "USER_EDIT_FILING_SUCCESS";
export const USER_EDIT_FILING_FAIL = "USER_EDIT_FILING_FAIL";

//Delete Leave Constants
export const USER_DELETE_FILING = "USER_DELETE_FILING";
