# Generated by Django 3.2 on 2021-04-28 06:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filings', '0003_auto_20210428_1438'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeaveCredits',
            new_name='LeaveCredit',
        ),
    ]
