# Generated by Django 3.2 on 2021-04-28 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filings', '0004_rename_leavecredits_leavecredit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filing',
            name='leave_credits',
        ),
        migrations.AddField(
            model_name='filing',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filings.leavetype'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filing',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_type',
            field=models.CharField(blank=True, choices=[(1, 'Work From Home'), (2, 'Sick Leave'), (3, 'Service Incentive Leave')], max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='LeaveCredit',
        ),
    ]
