# Generated by Django 3.2 on 2021-04-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0005_auto_20210428_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('1', 'Work From Home'), ('2', 'Sick Leave'), ('3', 'Service Incentive Leave')], max_length=250, null=True),
        ),
    ]
