# Generated by Django 3.2 on 2021-04-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0008_auto_20210428_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filing',
            name='day_type',
            field=models.CharField(choices=[('1', 'First Half'), ('2', 'Second Half'), ('3', 'Whole day')], default=3, max_length=50),
        ),
        migrations.AlterField(
            model_name='filing',
            name='leave_date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filing',
            name='leave_date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
