# Generated by Django 3.2 on 2021-04-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0014_alter_filing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filing',
            name='leave_date_from',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='filing',
            name='leave_date_to',
            field=models.DateField(auto_now_add=True),
        ),
    ]
