# Generated by Django 3.2 on 2021-05-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0016_auto_20210428_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Approve'), ('3', 'Rejected')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='filing',
            name='day_type',
            field=models.CharField(choices=[('1', 'First Half'), ('2', 'Second Half'), ('3', 'Whole day')], default='3', max_length=50),
        ),
    ]
