# Generated by Django 3.2 on 2021-05-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0018_auto_20210502_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filing',
            name='day_type',
            field=models.CharField(choices=[('1', 'First Half'), ('2', 'Second Half'), ('3', 'Whole day')], default='3', max_length=50),
        ),
        migrations.AlterField(
            model_name='filing',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Approve'), ('3', 'Rejected')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('1', 'Work From Home'), ('2', 'Sick Leave'), ('3', 'Service Incentive Leave')], max_length=250, null=True),
        ),
    ]
