# Generated by Django 3.2 on 2021-05-06 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0021_alter_leavetype_leave_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filings.filing')),
            ],
        ),
    ]
