# Generated by Django 3.2 on 2021-05-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0022_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='hr',
            field=models.CharField(blank=True, choices=[(1, 'admin@aljaybiosciences.com'), (5, 'drei@gmail.com'), (24, 'joke@gmail.com')], max_length=250, null=True),
        ),
    ]
