# Generated by Django 3.2 on 2021-05-06 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filings', '0023_approval_hr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='hr',
        ),
        migrations.AddField(
            model_name='approval',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Approve'), ('3', 'Rejected')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='approval',
            name='filing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filings.filing'),
        ),
    ]
