# Generated by Django 3.2 on 2021-05-06 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0024_auto_20210506_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='filing',
        ),
        migrations.AddField(
            model_name='filing',
            name='approvalStage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filings.approval'),
        ),
    ]
