# Generated by Django 3.2 on 2021-05-06 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0026_remove_filing_approvalstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='filing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filings.filing'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='approver',
            field=models.EmailField(max_length=254),
        ),
    ]
