# Generated by Django 3.2 on 2021-05-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0028_alter_approval_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='level',
            field=models.SmallIntegerField(default=0),
        ),
    ]
