# Generated by Django 3.2 on 2021-05-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0030_alter_filing_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filing',
            name='leave_date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filing',
            name='leave_date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
