# Generated by Django 3.2 on 2021-05-08 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0031_auto_20210507_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filing',
            name='status',
        ),
    ]
