# Generated by Django 3.2 on 2021-05-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0033_filing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
