# Generated by Django 3.2 on 2021-05-18 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0034_approval_remarks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Approval',
        ),
    ]
