# Generated by Django 3.2 on 2021-06-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0036_remove_filing_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filing',
            options={'ordering': ['-leave_date_from']},
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_credits',
            field=models.FloatField(default=0),
        ),
    ]
